version: '3'

services:

  #web:
  #  build:
  #    context: .
  #    dockerfile: ./docker/web/Dockerfile
  #  ports:
  #    - "89:80"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: holyroller
      MYSQL_USER: holy
      MYSQL_PASSWORD: roller
    ports:
      - "3389:3306"
